### ISSUE TITLE
Error in consensus mode 

### ISSUE THREAD

**Issue by tmc-hematopath** [pughlab/ConsensusCruncher#20]
Hi,  
  
We ran ConsensusCruncher.py fastq2bam on the LargeMid_56 fastq files provided in the test directory. The barcode-extracted fastq files and subsequently the BWA aligned BAMfile were generated without any errors.  
  
ConsensusCruncher.py consensus was run with the following command:  
`python3 ~/testing/duplex/ConsensusCruncher/ConsensusCruncher.py consensus -i ~/testing/duplex/results/largemid/output/bamfiles/LargeMid_56_L005_R1.fastq.sorted.bam -o ~/testing/duplex/results/largemid/output/consensus_output/ -s ~/programs/samtools-1.3.1/samtools --cleanup True --cutoff 0.7 -b ~/testing/duplex/ConsensusCruncher/ConsensusCruncher/hg19_cytoBand.txt`  
  
This gives the following error:
~~~
# === SSCS ===
Uncollapsed - Total reads: 19579
Uncollapsed - Unmapped reads: 0
Uncollapsed - Secondary/Supplementary reads: 0
SSCS reads: 0
Singletons: 0
Bad spacers: 19579

# QC: Total uncollapsed reads should be equivalent to mapped reads in bam file.
Total uncollapsed reads: 19579
Total mapped reads in bam file: 19562
QC: check dictionaries to see if there are any remaining reads
=== pair_dict remaining ===
=== read_dict remaining ===
=== csn_pair_dict remaining ===
Traceback (most recent call last):
  File "/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/SSCS_maker.py", line 391, in <module>
    main()
  File "/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/SSCS_maker.py", line 374, in main
    plt.xlim([0, math.ceil(lst_tags_per_fam[-1][0]/10) * 10])
IndexError: list index out of range
# === DCS ===
SSCS - Total reads: 0
SSCS - Unmapped reads: 0
SSCS - Secondary/Supplementary reads: 0
DCS reads: 0
SSCS singletons: 0 

Traceback (most recent call last):
  File "/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/singleton_correction.py", line 320, in <module>
    main()
  File "/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/singleton_correction.py", line 291, in main
    sscs_correction_frac = (sscs_dup_correction/singleton_counter) * 100
ZeroDivisionError: division by zero
# === DCS - Singleton Correction ===
SSCS SC - Total reads: 0
SSCS SC - Unmapped reads: 0
SSCS SC - Secondary/Supplementary reads: 0
DCS SC reads: 0
SSCS SC singletons: 0 

/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/SSCS_maker.py --infile /scratch/hematopath/testing/duplex/results/largemid/output/bamfiles/LargeMid_56_L005_R1.fastq.sorted.bam --outfile /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs/LargeMid_56_L005_R1.fastq.sorted.sscs.bam --cutoff 0.7 --bedfile /scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/hg19_cytoBand.txt --bdelim None
/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/DCS_maker.py --infile /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs/LargeMid_56_L005_R1.fastq.sorted.sscs.sorted.bam --outfile /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/dcs/LargeMid_56_L005_R1.fastq.sorted.dcs.bam --bedfile /scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/hg19_cytoBand.txt
/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/singleton_correction.py --singleton /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs/LargeMid_56_L005_R1.fastq.sorted.singleton.sorted.bam --bedfile /scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/hg19_cytoBand.txt
/scratch/hematopath/programs/samtools-1.7/samtools merge /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs_sc/LargeMid_56_L005_R1.fastq.sorted.sscs.sc.bam /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs/LargeMid_56_L005_R1.fastq.sorted.sscs.sorted.bam /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs_sc/LargeMid_56_L005_R1.fastq.sorted.sscs.correction.sorted.bam /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs_sc/LargeMid_56_L005_R1.fastq.sorted.singleton.correction.sorted.bam
/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/DCS_maker.py --infile /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs_sc/LargeMid_56_L005_R1.fastq.sorted.sscs.sc.sorted.bam --outfile /scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/dcs_sc/LargeMid_56_L005_R1.fastq.sorted.dcs.sc.bam --bedfile /scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher/hg19_cytoBand.txt
/scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/dcs_sc/LargeMid_56_L005_R1.fastq.sorted.all.unique.dcs.bam
Traceback (most recent call last):
  File "/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher.py", line 484, in <module>
    args.func(args)
  File "/scratch/hematopath/testing/duplex/ConsensusCruncher/ConsensusCruncher.py", line 301, in consensus
    '{}/{}_tag_fam_size.png'.format(sample_dir, identifier))
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/sscs/LargeMid_56_L005_R1.fastq.sorted_tag_fam_size.png' -> '/scratch/hematopath/testing/duplex/results/largemid/output/consensus_output//LargeMid_56_L005_R1.fastq.sorted/LargeMid_56_L005_R1.fastq.sorted_tag_fam_size.png'
~~~

**System**
OS: RHEL(7.3)
Other software versions:
    Python 3.7.4
    BWA 0.7.15
    Samtools 1.3.1

  
  
We are unable to figure out what could be causing these errors and would be extremely grateful if you can help us with this.  
Thanks

**Comment by arnavaz** [comment]
Hi,
Could you please provide us with the scripts and config files that you used along with the list of barcodes you used?
Also could you please send us the stats files from the extract barcode step? 
Thanks!
Arna

**Comment by arnavaz** [comment]
The issue was resolved. We modified the ConsensusCruncher.py so that there exist default values in case one does not use a config file. Please check out the latest commit.
